### ISSUE TITLE
The support ticket response email shows JSON data

### ISSUE THREAD

**Issue by danlipert** [HoardInvest/hoard#102]
May be an issue with erebor... 

![img_2047](https://user-images.githubusercontent.com/869266/42812846-dfd90a60-89f9-11e8-9f1c-c849a538ac91.JPG)

**Comment by danlipert** [comment]
Also note the emoji didn't show up correctly

**Comment by psiofxt** [comment]
Erebor PR [#90](https://github.com/HoardInvest/erebor/pull/90) fixes this

**Comment by psiofxt** [comment]
Merged.
