### ISSUE TITLE
When requesting payment, clicking on the requesting from field opens the recipient page, but cannot select anything.

### ISSUE THREAD

**Issue by markpeo** [HoardInvest/hoard#139]
android - samsung s9+
v 1.8

![screenshot_20180803-105651_hoard](https://user-images.githubusercontent.com/38840743/43655523-23ea24ea-970c-11e8-8ea3-ec55198a9601.jpg)

**Comment by zachgibb** [comment]
when you encountered this, were you logged in?

**Comment by markpeo** [comment]
Oh right, yes. Was not logged in.
When logged in, the only option I get is to select or enter contact. Then when, clicking on that option, app crashes as per open issue #130

**Comment by zachgibb** [comment]
Ok. Awesome. So I think the bug here is that the request portion was available to you at all when logged out - we would only be able to support requests / contact sends when logged in.

I'm working on addressing various bugs today, so I should be able to investigate this soon

**Comment by zachgibb** [comment]
addressed by commit 88f71db in PR #140
