### ISSUE TITLE
Requests cause the app to crash

### ISSUE THREAD

**Issue by danlipert** [HoardInvest/hoard#183]
"I tried to use the request function, but after clicking on the request from field, the pop up to allow the hoard app to access contacts showed up. When I clicked allow, the app crashed. Now when I try, I do not get the pop-up, but the app still crashes. I could send logs using Logcat, if that would help."

**Comment by ericgibb** [comment]
out-of-date now; requests have been removed

**Comment by zachgibb** [comment]
requests are still available - you just have to be signed in to do it. however, we did fix this issue though
