### ISSUE TITLE
Release Notes showing incorrect version number

### ISSUE THREAD

**Issue by danlipert** [HoardInvest/hoard#195]
"I was trying to check the wallet to determine which version I was on in the about section, but didn’t see anywhere that would display that information. I was mainly doing so to assist in Support cases where we have users saying ETH is not displaying. 

While doing so, I clicked the Release Notes page and noticed it still says Release 1.0 instead of 1.8 per the screenshot below. While likely not relevant for this instance, I am using an iPhone XS on version 12.0.1. I have also upgraded the Hoard wallet to 1.8."

**Comment by danlipert** [comment]
![version](https://user-images.githubusercontent.com/869266/47637338-b43ccf80-db9e-11e8-9a64-42e63ceab165.png)

**Comment by ericgibb** [comment]
this is out-of-date and no longer relevant. we've revamped the release notes screen.
