### ISSUE TITLE
Answering second question first on seed word quiz makes form unselectable

### ISSUE THREAD

**Issue by danlipert** [HoardInvest/hoard#273]
If a user enters the second word first in the seed word quiz, this makes the inputs unselectable, and the user must go to the previous screen and then forward again to proceed (and re-do the seed quiz).

**Comment by zachgibb** [comment]
i haven't actually been able to replicate this... i did a fresh install and tested both the wallet import and new wallet generation

**Comment by zachgibb** [comment]
Clarification: the error message is _above_ the underline of the input (it should be below the line), making it seem like the error message is the input itself. Additionally, tapping this error message does not focus the real input, making it seem like the input itself is broken.

Two actionable bugs from this:
1) The error message should be shown beneath the underline of the input
1) Tapping the error message of an input should focus that input
