### ISSUE TITLE
Change password menu item is not tappable until screen is scrolled

### ISSUE THREAD

**Issue by danlipert** [HoardInvest/hoard#288]
In the settings menu where you can change your password, for someone reason the change password menu item is non-interactable until you scroll the menu items.

**Comment by ericgibb** [comment]
I can not reproduce this in the simulator nor on device.

**Comment by danlipert** [comment]
@ericgibb I'll try to get a recording once we fix the "unidentified device" bugs and I can log in

**Comment by danlipert** [comment]
Fixed in 1.16 👍
