### ISSUE TITLE
No sent transactions in ETH transaction history

### ISSUE THREAD

**Issue by danlipert** [HoardInvest/hoard#300]
When I sent the transactions mentioned in the previous issue, after rebooting the app they didn't appear in the transaction history. https://etherscan.io/address/0x14fb661c402d4903afbc10830aa69cde5e57b379

**Comment by psiofxt** [comment]
This was an issue in quickblocks where the new cache wasn't assigned to the proper folder -- fixed!

**Comment by zachgibb** [comment]
If this was the same wallet as #301, @danlipert, could you see if that issue is resolved by the cache fix as well? That would explain the lack of a graph, as well

**Comment by danlipert** [comment]
Fixed by the cache fix!
