### ISSUE TITLE
Sometimes the back button freezes up - screen eventually pops

### ISSUE THREAD

**Issue by danlipert** [HoardInvest/hoard#312]
First seen in 1.16, sometimes the back button becomes unresponsive for a few seconds. Then, without tapping it again, the screen will pop back as normal.

**Comment by danlipert** [comment]
In general something odd is happening - things seem to randomly freeze up and affect a bunch of things in the app, (QR code scanning, seed word display, etc..) I'm guessing it has something to do with the polling for txns.

**Comment by zachgibb** [comment]
I was not able to replicate this, but I did add areas where rendering was allowed to happen more smoothly in #320
