### ISSUE TITLE
After sending txn - all the individual wallets show spinners instead of going to the wallet

### ISSUE THREAD

**Issue by danlipert** [HoardInvest/hoard#313]
Aftering initiating a BTC send, all of the individual wallet screens only show a spinner. Restarting the app restores the functionality.

**Comment by danlipert** [comment]
This also happens with RVN

**Comment by danlipert** [comment]
Also happens with HOARD - probably also with ETH ;)

**Comment by zachgibb** [comment]
i'm pretty sure this will be fixed by, but i would love to get a confirmation of this once a build goes out #321

**Comment by zachgibb** [comment]
also, this issue is a duplicate of #299
